# - Device Configuration -
# The Path to look for the file(s) that represent the Device Information Models to load into the Agent.
# The path can either be a single file or a directory.
# The path can be absolute or relative to the executable's directory
devices: devices

# - SHDR Adapter Configuration -
# The Agent is able to receive data through a TCP port using the SHDR protocol
adapters:
- hostname: localhost
  port: 7878
  reconnectInterval: 1000

# Sets whether a Device Model can be sent from an SHDR Adapter
allowShdrDevice: false


# - Windows Service Configuration

# Changes the service name when installing or removing the service. This allows multiple agents to run as services on the same machine.
serviceName: MTConnect-Agent-HTTP

# Sets the Service Start Type. True = Auto | False = Manual
serviceAutoStart: true


# - HTTP Server Configuration -
# The Agent is able to respond to requests using the Http REST protocol described in the MTConnect Standard.
# The server supports response compression and serving of Static files (Files configuration)

# The server IP Address to bind to. Can be used to select the interface in IPV4 or IPV6.
# Change this to the server's IP hostname
# serverIp: localhost

# The port number the agent binds to for requests.
port: 5000

# List of Encodings (ex. gzip, br, deflate) to pass to the Accept-Encoding HTTP Header
responseCompression:
- gzip
- br

# Allow HTTP PUT or POST of data item values or assets.
allowPut: true

# The maximum number of Threads to use for the Http Stream Requests
# If client receives Service Unavailable : 503 HTTP Status Code, this value can be increased as needed. CPU and Memory resource usage increases as this value increases
maxStreamingThreads: 5

# Sets the default response document indendation
indentOutput: true

# Sets the default response document comments output. Comments contain descriptions from the MTConnect standard
# This is typically just used for debugging or for demo purposes
outputComments: false

# Configuration for Static Files that can be served from the Http Server
files:
- path: schemas
  location: schemas
- path: styles
  location: styles
- path: styles/favicon.ico
  location: favicon.ico

# Configuration for XML Stylesheets for MTConnectStreamsResponse documents (Current and Samples requests)
streamsStyle:
  location: styles/stylesheet-streams.xsl


# - Buffer Configuration -
# The Agent has an internal buffer that retains the information that the Agent can respond with according to the MTConnect Standard.
# There is also a Durable File backed buffer that can retain the information in the Agent between Agent restarts

# The maximum number of Observations the agent can hold in its buffer
observationBufferSize: 150000

# The maximum number of assets the agent can hold in its buffer
assetBufferSize: 1000

# Sets whether the Agent buffers are durable and retain state after restart
durable: false

# Sets whether the durable Agent buffers use Compression
useBufferCompression: false


# - Agent Configuration -

# Sets the default MTConnect version to output response documents for.
defaultVersion: 2.1

# Overwrite timestamps with the agent time. This will correct clock drift but will not give as accurate relative time since it will not take into consideration network latencies. This can be overridden on a per adapter basis.
ignoreTimestamps: false

# Sets the default for Converting Units when adding Observations
convertUnits: true

# Sets the default for Ignoring the case of Observation values. Applicable values will be converted to uppercase
ignoreObservationCase: true

# Sets the default input validation level when new Observations are added to the Agent. 0 = Ignore, 1 = Warning, 2 = Strict
inputValidationLevel: Ignore

# Sets whether Configuration files are monitored. If enabled and a configuration file is changed, the Agent will restart
monitorConfigurationFiles: true

# Sets the minimum time (in seconds) between Agent restarts when MonitorConfigurationFiles is enabled
configurationFileRestartInterval: 2

# Sets whether Agent Metrics are captured (ex. ObserationUpdateRate, AssetUpdateRate)
enableMetrics: true
